name = "stefanuk12/laminar_fluent"
description = "A proper rewrite of the Fluent UI Library."
version = "0.1.0"
authors = ["Stefanuk12 <stefan@petrovic.foo>"]
license = "MIT"
includes = ["pesde.toml", "README.md", "LICENSE", "src/*"]

[engines]
# pesde = "^0.6.2"
lune = "=0.8.9"

[target]
build_files = ["src"]
environment = "roblox"
lib = "src/init.luau"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
flipper = { wally = "reselim/flipper", version = "^2.0.0" }
signal = { name = "jiwonz/signal", version = "^0.1.0" }
trove = { wally = "sleitnick/trove", version = "^1.5.1" }

[dev_dependencies]
darklua = { repo = "Stefanuk12/darklua", rev = "3af4b5a642ddda5141cfb086021626c97f82047d", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.2", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.42.1", target = "lune" }
selene = { name = "pesde/selene", version = "^0.28.0", target = "lune" }
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
luau_defs = { repo = "rocult/luau-defs", rev = "main" }
